### ISSUE TITLE
Program crashing when running buffer tool

### ISSUE THREAD

**Issue by msNETL** [NETL-RIC/GISA-testing-issues#10]
***Note:*** Edited for format clarity. -PW

I used State Layer on the buffer

**Error from cmd console** 
----
```
Traceback (most recent call last):
  File "gisalib\ui_qt\location_tab.py", line 188, in _refresh_map
  File "gisalib\controllers\location_controller.py", line 198, in apply_buffer
  File "gisalib\controllers\LocationAnonymizer.py", line 54, in apply_constraint
KeyError: 'Census_Tract'
PS C:\Users\sharmam\Documents\02_DataWorking\Task_46_Data Annonymization\GISA> Traceback (most recent call last):
most : The term 'most' is not recognized as the name of a cmdlet, function, script file, or operable program. Check
the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:12
+ Traceback (most recent call last):
+            ~~~~
    + CategoryInfo          : ObjectNotFound: (most:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\sharmam\Documents\02_DataWorking\Task_46_Data Annonymization\GISA>   File "gisalib\ui_qt\location_tab.py", line 188, in _refresh_map
File : The term 'File' is not recognized as the name of a cmdlet, function, script file, or operable program. Check
the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:3
+   File "gisalib\ui_qt\location_tab.py", line 188, in _refresh_map
+   ~~~~
    + CategoryInfo          : ObjectNotFound: (File:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\sharmam\Documents\02_DataWorking\Task_46_Data Annonymization\GISA>   File "gisalib\controllers\location_controller.py", line 198, in apply_buffer
File : The term 'File' is not recognized as the name of a cmdlet, function, script file, or operable program. Check
the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:3
+   File "gisalib\controllers\location_controller.py", line 198, in app ...
+   ~~~~
    + CategoryInfo          : ObjectNotFound: (File:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\sharmam\Documents\02_DataWorking\Task_46_Data Annonymization\GISA>   File "gisalib\controllers\LocationAnonymizer.py", line 54, in apply_constraint
File : The term 'File' is not recognized as the name of a cmdlet, function, script file, or operable program. Check
the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:3
+   File "gisalib\controllers\LocationAnonymizer.py", line 54, in apply ...
+   ~~~~
    + CategoryInfo          : ObjectNotFound: (File:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\sharmam\Documents\02_DataWorking\Task_46_Data Annonymization\GISA> KeyError: 'Census_Tract'
KeyError: : The term 'KeyError:' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ KeyError: 'Census_Tract'
+ ~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (KeyError::String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\sharmam\Documents\02_DataWorking\Task_46_Data Annonymization\GISA> PS C:\Users\sharmam\Documents\02_DataWorking\Task_46_Data Annonymization\GISA>Traceback (most recent call last):
most : The term 'most' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path
is correct and try again.
At line:1 char:90
+ ... _DataWorking\Task_46_Data Annonymization\GISA>Traceback (most recent  ...
+                                                              ~~~~
    + CategoryInfo          : ObjectNotFound: (most:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\sharmam\Documents\02_DataWorking\Task_46_Data Annonymization\GISA>   File "gisalib\ui_qt\location_tab.py", line 188, in _refresh_map
File : The term 'File' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path
is correct and try again.
At line:1 char:3
+   File "gisalib\ui_qt\location_tab.py", line 188, in _refresh_map
+   ~~~~
    + CategoryInfo          : ObjectNotFound: (File:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\sharmam\Documents\02_DataWorking\Task_46_Data Annonymization\GISA>   File "gisalib\controllers\location_controller.py", line 198, in apply_buffer
File : The term 'File' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path
is correct and try again.
At line:1 char:3
+   File "gisalib\controllers\location_controller.py", line 198, in app ...
+   ~~~~
    + CategoryInfo          : ObjectNotFound: (File:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\sharmam\Documents\02_DataWorking\Task_46_Data Annonymization\GISA>   File "gisalib\controllers\LocationAnonymizer.py", line 54, in apply_constraint
File : The term 'File' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path
is correct and try again.
At line:1 char:3
+   File "gisalib\controllers\LocationAnonymizer.py", line 54, in apply ...
+   ~~~~
    + CategoryInfo          : ObjectNotFound: (File:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\sharmam\Documents\02_DataWorking\Task_46_Data Annonymization\GISA> KeyError: 'Census_Tract'
KeyError: : The term 'KeyError:' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that
the path is correct and try again.
At line:1 char:1
+ KeyError: 'Census_Tract'
+ ~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (KeyError::String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\sharmam\Documents\02_DataWorking\Task_46_Data Annonymization\GISA> PS C:\Users\sharmam\Documents\02_DataWorking\Task_46_Data Annonymization\GISA>Traceback (most recent call last):
most : The term 'most' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path
is correct and try again.
At line:1 char:90
+ ... _DataWorking\Task_46_Data Annonymization\GISA>Traceback (most recent  ...
+                                                              ~~~~
    + CategoryInfo          : ObjectNotFound: (most:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\sharmam\Documents\02_DataWorking\Task_46_Data Annonymization\GISA>   File "gisalib\ui_qt\location_tab.py", line 188, in _refresh_map
File : The term 'File' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path
is correct and try again.
At line:1 char:3
+   File "gisalib\ui_qt\location_tab.py", line 188, in _refresh_map
+   ~~~~
    + CategoryInfo          : ObjectNotFound: (File:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\sharmam\Documents\02_DataWorking\Task_46_Data Annonymization\GISA>   File "gisalib\controllers\location_controller.py", line 198, in apply_buffer
File : The term 'File' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path
is correct and try again.
At line:1 char:3
+   File "gisalib\controllers\location_controller.py", line 198, in app ...
+   ~~~~
    + CategoryInfo          : ObjectNotFound: (File:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\sharmam\Documents\02_DataWorking\Task_46_Data Annonymization\GISA>   File "gisalib\controllers\LocationAnonymizer.py", line 54, in apply_constraint
File : The term 'File' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path
is correct and try again.
At line:1 char:3
+   File "gisalib\controllers\LocationAnonymizer.py", line 54, in apply ...
+   ~~~~
    + CategoryInfo          : ObjectNotFound: (File:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\sharmam\Documents\02_DataWorking\Task_46_Data Annonymization\GISA> KeyError: 'Census_Tract'
KeyError: : The term 'KeyError:' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that
the path is correct and try again.
At line:1 char:1
+ KeyError: 'Census_Tract'
+ ~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (KeyError::String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\sharmam\Documents\02_DataWorking\Task_46_Data Annonymization\GISA> PS C:\Users\sharmam\Documents\02_DataWorking\Task_46_Data Annonymization\GISA>
--------------------------------------------
```

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

** Stack Trace **
screen shot or copy/past of stack trace, if available.

**Additional context**

**Comment by michael-c-gao** [comment]
Hi Maneesh, which shapefile were you using to test that produced these errors?

**Comment by msNETL** [comment]
Michael, I was using CarbonSAFE_Projects_60_Points.shp

**Comment by michael-c-gao** [comment]
fixed, state layer now works
