### ISSUE TITLE
Failed Export with LSH

### ISSUE THREAD

**Issue by irpfander** [NETL-RIC/GISA-testing-issues#2]
Export failed after importing csv, setting lat/lon, plotting data with LSH anonymization and then clicking export data and selecting output folder. I was not able to recreate the issue. On subsequent tries with the same data, export worked successfully. 

Input dataset (for testing again): WI_Power_Plant_Outfalls_processed2.csv

Traceback (most recent call last):
  File "gisalib\ui_qt\location_tab.py", line 244, in _exportfile
  File "gisalib\controllers\location_controller.py", line 109, in exportcsv
  File "pandas\core\frame.py", line 5685, in pop
  File "pandas\core\generic.py", line 923, in pop
  File "pandas\core\frame.py", line 3807, in __getitem__
  File "pandas\core\indexes\base.py", line 3804, in get_loc
KeyError: 'Random_Lat'

**Comment by michael-c-gao** [comment]
@irpfander Can you send me the file you were using to test?

**Comment by irpfander** [comment]
here it is @michael-c-gao  [GISA test data.zip](https://github.com/NETL-RIC/GISA-testing-issues/files/12032295/GISA.test.data.zip)

**Comment by michael-c-gao** [comment]
Fixed, was an issue when exporting multiple times with the same file
